### ISSUE TITLE
GWTimes / IoTVideo-iOS Demo 运行错误

### ISSUE THREAD

**Issue by laqlsqlsq** [GWTimes/IoTVideo-iOS#6]
我今天更新了贵公司的SDK，但是出现了新的问题,提示“Missing required modules:'IVLog','IVNetwork'”

**Comment by GWTimes** [comment]
是因为Swift的Framework网络组件引入了modulemap引起的该问题，现阶段暂时将网络组件单独打包成Framework解决该问题，请重新更新代码即可运行。

**Comment by GWTimes** [comment]
> 我今天更新了贵公司的SDK，但是出现了新的问题,提示“Missing required modules:'IVLog','IVNetwork'”

是因为Swift的Framework网络组件引入了modulemap引起的该问题，现阶段暂时将网络组件单独打包成Framework解决该问题，请重新更新代码即可运行。

**Comment by GWTimes** [comment]
> 我今天更新了贵公司的SDK，但是出现了新的问题,提示“Missing required modules:'IVLog','IVNetwork'”

是因为Swift的Framework网络组件引入了modulemap引起的该问题，现阶段暂时将网络组件单独打包成Framework解决该问题，请重新更新代码即可运行。
